package com.takumalee.ormcomparison.database.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHARACTER".
 */
public class Character {

    private Long id;
    /** Not-null value. */
    private String careers;
    /** Not-null value. */
    private String attributes;

    public Character() {
    }

    public Character(Long id) {
        this.id = id;
    }

    public Character(Long id, String careers, String attributes) {
        this.id = id;
        this.careers = careers;
        this.attributes = attributes;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCareers() {
        return careers;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCareers(String careers) {
        this.careers = careers;
    }

    /** Not-null value. */
    public String getAttributes() {
        return attributes;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

}
