package com.takumalee.ormcomparison.database.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.takumalee.ormcomparison.database.greendao.dao.Character;

import com.takumalee.ormcomparison.database.greendao.dao.CharacterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig characterDaoConfig;

    private final CharacterDao characterDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        characterDaoConfig = daoConfigMap.get(CharacterDao.class).clone();
        characterDaoConfig.initIdentityScope(type);

        characterDao = new CharacterDao(characterDaoConfig, this);

        registerDao(Character.class, characterDao);
    }
    
    public void clear() {
        characterDaoConfig.getIdentityScope().clear();
    }

    public CharacterDao getCharacterDao() {
        return characterDao;
    }

}
